CREATE TABLE Ongs(
	Id INT PRIMARY KEY,
	Nome VARCHAR(50) NOT NULL,
	Cnpj VARCHAR(14) UNIQUE NOT NULL,
	Endereco VARCHAR(50),
	Telefone VARCHAR(11) UNIQUE NOT NULL,
	Email VARCHAR(50) UNIQUE NOT NULL,
	Descricao VARCHAR(100)
);

CREATE TABLE Voluntarios(
	Id INT PRIMARY KEY,
	Nome VARCHAR(50) NOT NULL,
	Endereco VARCHAR(50) NOT NULL,
	Telefone VARCHAR(11) UNIQUE NOT NULL,
	Email VARCHAR(50) UNIQUE NOT NULL,
	Nascimento DATE NOT NULL,
	IdOng INT NOT NULL,

	FOREIGN KEY (IdOng) REFERENCES Ongs(Id)
);

CREATE TABLE Doadores(
	Id INT PRIMARY KEY,
	Nome VARCHAR(50) NOT NULL,
	Endereco VARCHAR(50) NOT NULL,
	Telefone VARCHAR(11) UNIQUE NOT NULL,
	Email VARCHAR(50) UNIQUE NOT NULL	
);

CREATE TABLE Doacoes(
	Id INT PRIMARY KEY,
	Data DATE NOT NULL,
	Valor FLOAT DEFAULT 0.0, 
	Tipo VARCHAR (20) NOT NULL,
	IdOng INT NOT NULL,

	FOREIGN KEY (IdOng) REFERENCES Ongs(Id)
	

	CHECK(Valor>=0.0)
	
)